version: '3.5'
services:
  db:
    image: postgres:latest
    hostname: db
    command: 'postgres -c max_connections=200 -c shared_buffers=256MB -c fsync=off -c full_page_writes=off'
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'
  api01:
    container_name: rinha-api01
    build: 
        context: .
    depends_on:
      - db
      - nats 
    environment:
      - ASPNETCORE_HTTP_PORTS=80
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.9GB'
  api02:
    container_name: rinha-api02
    build: 
        context: .
    depends_on:
      - db
      - nats 
    environment:
      - ASPNETCORE_HTTP_PORTS=80
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.9GB'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  nats:
    hostname: nats
    image: nats:latest
    ports:
      - '4222:4222'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'
networks:
  default:
    driver: bridge
    name: rinha