version: '3.5'
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    deploy:
      resources:
        limits:
          cpus: '0.95'
          memory: '1.6GB'
  api01:
    container_name: rinha-api01
    build: 
        context: .
    depends_on:
      - db
    environment:
      - ASPNETCORE_HTTP_PORTS=80
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '0.75GB'
  api02:
    container_name: rinha-api02
    build: 
        context: .
    depends_on:
      - db
    environment:
      - ASPNETCORE_HTTP_PORTS=80
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.4GB'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.3GB'
  redis:
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'

networks:
  default:
    driver: bridge
    name: rinha